### ISSUE TITLE
Not being able to convert to steam save data

### ISSUE THREAD

**Issue by Wasbu** [Thurler/thlaby2-save-convert#2]
this post is quite old and im hoping ill get a answer!
but following the instructions, installing python and putting the convertor in the save data folder
its not giving me a result.dat file?
i see the CMD app open for a second and close immediately after.
![image](https://github.com/user-attachments/assets/da8e006d-7240-4c1d-9ea6-965a38ec562f)
these are all my files for the save

**Comment by Thurler** [comment]
Hey there, my guess here is that the script is failing to convert things because you're missing the Plus Disk files, and I never added checks to make sure those files exist. Would you mind confirming if that's the case, and which version of the game this save is from?

Additionally, if you could follow these steps so I can get a proper look at the script's error:

- In the save directory, hold `Shift` and right click on an empty area, then select `Open in Terminal` (Win11) or `Open PowerShell window here` (Win10)

![image](https://github.com/user-attachments/assets/3c82b250-aa0e-424c-ba9b-939329b5ac93)

- A new window with a terminal should have popped up, type `python convert_save.py` on it and hit `Enter`. This window might have a blue background instead of a black one

![image](https://github.com/user-attachments/assets/ebbedaa9-9f94-4e47-9beb-e703271aed12)

An error message like this one should show up, saying that a file could not be located. I tried running it on a save from the base game's 1.203 version, so I can confirm there will be an error if the Plus Disk files are missing. I'd just like to know if this is the exact error you got, in case there's something more to look into.

**Comment by Wasbu** [comment]
![image](https://github.com/user-attachments/assets/12ed7dea-4a4c-4b80-9542-03606a356934)

ahh i see. my ver of LoT2 doesnt have plus disk lol (that makes alot of sense now -_-)
I assume getting the plus disk patch would make the converter work?

edit : i was looking into plus disk and its 8 dollars. which i feel iffy (just cuz i bought the steam ver lol) didnt mind buying it but DLsite removed mastercard/visa (love censorship www) so i was wondering if theres any other way of going about it?

**Comment by Thurler** [comment]
> I assume getting the plus disk patch would make the converter work?

Correct, but as you mentioned, it costs some money that you shouldn't be spending, considering you've already bought the Steam version of the game after all.

It should be a simple fix on the script to ignore the missing files and treat them as if they were all blank, considering the missing files are for PD characters and dungeon data. If you give me a few days I can cook a new version that's compatible with the old save format.

Another alternative is for you to zip your save file and attach it here, I can convert it for you to the PD format using my copy of the game, and then to the Steam format with the script.

I'm also attaching a **blank save file** from my copy of PD, if you want to try harvesting the missing files from it - I have no idea how the conversion process would go, so **PLEASE make a backup of your save file** if you'll attempt this.

[blanksave.zip](https://github.com/user-attachments/files/18224622/blanksave.zip)

**Comment by Wasbu** [comment]
Seems like copying all the PD files from the blank save into my save made the converter work!
All my data seems intact with no issue
Thank you so much for helping! i can continue playing LoT2 now www
